### ISSUE TITLE
7.3.3.9 - pja - Why json prefix for jsonFormat and jsonPattern?

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#21]
The TV's _jsonPattern_ and _jsonFormat_both have the _json_ prefix. Is that really needed? I would expect the pattern and format be equal in any implementation. Or do we foresee _ldPattern_, _gmlPattern_ etc?

**Comment by jechterhoff** [comment]
Re _jsonPattern_: We did that since different implementation technologies may support different regular expression dialects. With the _json_ prefix, we ensure that the pattern value is used specifically written for use in JSON Schema. If we come across other implementation technologies that have their own regex dialect, then the definition of specific _xyzPattern_ tags may be justified. Of course, there may be precedent for a plain _pattern_ tag, as is the case in ShapeChange for the XSD encoding. There may even be a non regex-related use of "pattern" in a certain implementation technology. That would be another reason to define a _xyzPattern_ tag (i.e., with technology specific prefix).

Re _jsonFormat_: Here the use is definitely restricted to JSON Schema, since the values of the tag shall be JSON Schema keywords.
