### ISSUE TITLE
Requirement 21 (/req/geojson-formats/identifier)

### ISSUE THREAD

**Issue by heidivanparys** [Geonovum/uml2json#40]
I am not sure that I understand note 2 of this requirement. There seems to be a contradiction here?

![image](https://user-images.githubusercontent.com/11427611/214024529-8e7f6339-b2e6-4fe8-933f-a18788f4810b.png)

**Comment by PalmJanssen** [comment]
What is meant is that:
1) the value of the UML property that has "isID"= true is mapped to the standard "id"member of the JSON feature.
2) the original UML property that has "isID" is also included in the data and encoded as any other property

**Comment by jechterhoff** [comment]
Maybe the requirement should be rephrased as follows: _If at least one UML property of a feature type is modeled with “isId” = true, then the top-level “id” member of GeoJSON features that encode instances of the feature type shall have a value._

And below the requirement, in normal text, we can add the following: _A UML property of a feature type, wich is modeled with “isId” = true, is mapped to the “id” member of a GeoJSON feature. The mapping algorithm is community-specific - especially if multiple such properties exist in a feature type._

The intent of the requirement is to state under which circumstance the top-level GeoJSON "id" member must have a value, so this is a requirement for instance data. The original phrasing is not perfect with respect to the first shall, because it cannot be tested - due to the mapping being community-specific.

@heidivanparys: Would that be better, in your view?

**Comment by heidivanparys** [comment]
@jechterhoff Yes, that would be better.

> And below the requirement, in normal text, we can add the following: _A UML property of a feature type, wich is modeled with “isId” = true, is mapped to the “id” member of a GeoJSON feature. The mapping algorithm is community-specific - especially if multiple such properties exist in a feature type._

Perhaps this text should be integrated in NOTE 1?

Minor additional comment on that piece of text:

A UML property of a feature type, wich is modeled with “isId” = true

should be

A UML property of a feature type which is modeled with “isId” = true

(so without comma, and with h)

> What is meant is that:
> 
> 1. the value of the UML property that has "isID"= true is mapped to the standard "id"member of the JSON feature.
> 2. the original UML property that has "isID" is also included in the data and encoded as any other property

@PalmJanssen In the second note, I am missing some text that explains this more explicitly. Perhaps "The UML properties with "isId" = true are encoded as any other property<ins>, in addition to being mapped to the top-level "id" member</ins>.".

**Comment by jechterhoff** [comment]
Issue #51 is related to this one.

**Comment by PalmJanssen** [comment]
> In the second note, I am missing some text that explains this more explicitly. Perhaps "The UML properties with "isId" = true are encoded as any other property, in addition to being mapped to the top-level "id" member.".

agreed
