### ISSUE TITLE
7.2 - pja - JSON encoding specific Tagged Values

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#9]
Table 3 shows that apparantly UML needs many JSON specific Tagged Values. This is quite a load for a UML application schema. How will that work? Should a EA profile for JSON be developed?

**Comment by jechterhoff** [comment]
In order to apply the tags in a UML 2 based model, stereotypes will have to be defined, and thus a UML profile. The question is whether we should go into more detail within the specification, or leave that as future work.

In fact, the UML profile would be what in [_Geospatial Data Modelling and Model-driven Transformation of Geospatial Data based on UML Proﬁles_](https://d-nb.info/1121779999/34) is called an _encoding UML profile_. 

The way in which the UML profile should be defined, especially with respect to practicality, would need further work (and may be out-of-scope for this project). Defining multiple UML profile packages, for conceptual and specific encoding purposes, and merging them into a community profile as needed, using the _package merge_ mechanism of UML, would be an interesting approach - but sadly does not seem to work in Sparx Systems Enterprise Architect (only modeling works out-of-the-box, but the actual merge seems to not directly be supported by EA).

**Comment by PalmJanssen** [comment]
agree
